// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "jungleman":return img`
........................
....ffffff..............
..ffeeeeeef.............
.ffeeeeeeeef............
.feeefffffffff.cc.......
.ffffeeeeeeeefcdc.......
.feeeeffffeefcdc........
.ffffffeeeffcdc.........
.fe44ebf44ecddc.........
.fe4d41fddecdc..........
.feee4dddedccc..........
..ffee44e4dde...........
...f666644ee............
...f6666e6f.............
...f444488f.............
....ffffff..............
.....fff................
........................
........................
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
